### PR TITLE
Update docs

### PR DESCRIPTION
**Pull request by williamcroberts**

### CODE REVIEW

**Review by gotthardp — CHANGES_REQUESTED** [review]
There is `tpm2-tss` on several places and the RELEASE.md duplicates the doc/RELEASE.md this project already has. I'd prefer to keep the current one as it has be carefully tailored.

**Comment by williamcroberts** [comment]
> There is `tpm2-tss` on several places and the RELEASE.md duplicates the doc/RELEASE.md this project already has. I'd prefer to keep the current one as it has be carefully tailored.

Oh I didn't see the doc/RELEASE.md, sorry. I will correct that.

**Comment by williamcroberts** [comment]
> > There is `tpm2-tss` on several places and the RELEASE.md duplicates the doc/RELEASE.md this project already has. I'd prefer to keep the current one as it has be carefully tailored.
> 
> Oh I didn't see the doc/RELEASE.md, sorry. I will correct that.

updated, sorry for the delay I forgot about this.

**Comment by gotthardp** [comment]
Thanks.

**Pull request merged**
